config/routes.rb
Rails.application.routes.draw do
  resources :sidekiq_plans
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sidekiq_plan.rb
class SidekiqPlan < ApplicationRecord
  enum status: {
    initial:  0,
    waiting:  1,
    started:  2,
    finished: 3,
    failed:   4,
  }

  def worker_class
    return @worker_class if defined?(@worker_class)
    @worker_class = worker_name.classify.constantize
  end

  def enqueue
    self.jid = worker_class.perform_at(perform_at, id)
    waiting!
  end

  def started!
    self.started_at = Time.current
    super
  end

  def finished!
    self.finished_at = Time.current
    super
  end

  def failed!
    self.finished_at = nil
    self.failed_at = Time.current
    super
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/sidekiq_plans_controller.rb
class SidekiqPlansController < ApplicationController
  before_action :set_sidekiq_plan, only: [:show, :edit, :update, :destroy]

  # GET /sidekiq_plans
  def index
    @sidekiq_plans = SidekiqPlan.all
  end

  # GET /sidekiq_plans/1
  def show
  end

  # GET /sidekiq_plans/new
  def new
    @sidekiq_plan = SidekiqPlan.new
  end

  # GET /sidekiq_plans/1/edit
  def edit
  end

  # POST /sidekiq_plans
  def create
    @sidekiq_plan = SidekiqPlan.new(sidekiq_plan_params)
    @sidekiq_plan.jid = 0
    @sidekiq_plan.status = :initial

    if @sidekiq_plan.save
      @sidekiq_plan.enqueue
      redirect_to @sidekiq_plan, notice: 'Sidekiq plan was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /sidekiq_plans/1
  def update
    if @sidekiq_plan.update(sidekiq_plan_params)
      redirect_to @sidekiq_plan, notice: 'Sidekiq plan was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /sidekiq_plans/1
  def destroy
    @sidekiq_plan.destroy
    redirect_to sidekiq_plans_url, notice: 'Sidekiq plan was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_sidekiq_plan
      @sidekiq_plan = SidekiqPlan.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def sidekiq_plan_params
      params.require(:sidekiq_plan).permit(:label, :worker_name, :perform_at)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sidekiq_plans_helper.rb
module SidekiqPlansHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SidekiqAdmin</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/sidekiq_plans/_form.html.erb
<%= form_with(model: sidekiq_plan, local: true) do |form| %>
  <% if sidekiq_plan.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(sidekiq_plan.errors.count, "error") %> prohibited this sidekiq_plan from being saved:</h2>

      <ul>
      <% sidekiq_plan.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :label %>
    <%= form.text_field :label %>
  </div>

  <div class="field">
    <%= form.label :worker_name %>
    <%= form.text_field :worker_name %>
  </div>

  <div class="field">
    <%= form.label :perform_at %>
    <%= form.datetime_field :perform_at %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/sidekiq_plans/edit.html.erb
<h1>Editing Sidekiq Plan</h1>

<%= render 'form', sidekiq_plan: @sidekiq_plan %>

<%= link_to 'Show', @sidekiq_plan %> |
<%= link_to 'Back', sidekiq_plans_path %>

app/views/sidekiq_plans/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Sidekiq Plans</h1>

<table>
  <thead>
    <tr>
      <th>Label</th>
      <th>Worker name</th>
      <th>Jid</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @sidekiq_plans.each do |sidekiq_plan| %>
      <tr>
        <td><%= sidekiq_plan.label %></td>
        <td><%= sidekiq_plan.worker_name %></td>
        <td><%= sidekiq_plan.jid %></td>
        <td><%= sidekiq_plan.status %></td>
        <td><%= link_to 'Show', sidekiq_plan %></td>
        <td><%= link_to 'Edit', edit_sidekiq_plan_path(sidekiq_plan) %></td>
        <td><%= link_to 'Destroy', sidekiq_plan, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Sidekiq Plan', new_sidekiq_plan_path %>

app/views/sidekiq_plans/new.html.erb
<h1>New Sidekiq Plan</h1>

<%= render 'form', sidekiq_plan: @sidekiq_plan %>

<%= link_to 'Back', sidekiq_plans_path %>

app/views/sidekiq_plans/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Label:</strong>
  <%= @sidekiq_plan.label %>
</p>

<p>
  <strong>Worker name:</strong>
  <%= @sidekiq_plan.worker_name %>
</p>

<p>
  <strong>Jid:</strong>
  <%= @sidekiq_plan.jid %>
</p>

<p>
  <strong>Status:</strong>
  <%= @sidekiq_plan.status %>
</p>

<%= link_to 'Edit', edit_sidekiq_plan_path(@sidekiq_plan) %> |
<%= link_to 'Back', sidekiq_plans_path %>